### ISSUE TITLE
GTK_IM_MODULE 无法确定 Fctix5 的存在

### ISSUE THREAD

**Issue by shenlebantongying** [marguerite/rime-plum-go#2]
上次我写的时候遇到过这个问题，那就是 fcitx5 继续在用 fcitx 的名字作为 IM_MODULE。

https://github.com/marguerite/rime-plum-go/blob/f177e9ead3cdfabbd4926a3acef7215a7dfdfa5e/frontend_unix.go#L10-L16

至少两个重要的来源 CS Slayer 和 Arch wiki 都写着 fcitx5 继续用 “GTK_IM_MODULE DEFAULT=fcitx”，，，，，，，，，，

https://www.csslayer.info/wordpress/fcitx-dev/如何现在就在-arch-linux-用上-fcitx-5/
https://wiki.archlinux.org/index.php/Fcitx5_(简体中文)#环境变量

**Comment by marguerite** [comment]
fixed
